import React from 'react';
import Svg, { Rect, Circle } from 'react-native-svg';

interface IconProps {
  size?: number;
  color: string;
}

// Minimal three-bar chart used for the roll-history (stats) button.
export const BarChartIcon: React.FC<IconProps> = ({ size = 24, color }) => (
  <Svg width={size} height={size} viewBox="0 0 24 24">
    <Rect x="3" y="13" width="4" height="8" rx="1" fill={color} />
    <Rect x="10" y="8" width="4" height="13" rx="1" fill={color} />
    <Rect x="17" y="3" width="4" height="18" rx="1" fill={color} />
  </Svg>
);

interface GearIconProps extends IconProps {
  // The center hole is punched using the page background colour.
  bgColor: string;
}

// Simple solid cog used for the settings button. Teeth are generated by
// rotating a single tooth around the centre, with a hole in the middle.
export const GearIcon: React.FC<GearIconProps> = ({ size = 24, color, bgColor }) => {
  const teeth = [];
  for (let i = 0; i < 8; i++) {
    teeth.push(
      <Rect
        key={i}
        x="10.6"
        y="1.5"
        width="2.8"
        height="5"
        rx="1"
        fill={color}
        transform={`rotate(${i * 45} 12 12)`}
      />
    );
  }
  return (
    <Svg width={size} height={size} viewBox="0 0 24 24">
      {teeth}
      <Circle cx="12" cy="12" r="7" fill={color} />
      <Circle cx="12" cy="12" r="3" fill={bgColor} />
    </Svg>
  );
};
